# Generated by Django 4.1 on 2023-11-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pntmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='123456ABCDE', max_length=50, unique=True),
        ),
    ]
