# Generated by Django 4.1 on 2023-11-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pntmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SKU',
            field=models.CharField(default='123456', max_length=50, unique=True),
        ),
    ]
