# Generated by Django 4.1 on 2023-11-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pntmodel', '0002_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='SKU',
        ),
    ]
