# Generated by Django 4.1 on 2023-11-13 18:01

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pntmodel', '0002_alter_siteuser_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='siteuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='shoporder',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='shoporder',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='category_id',
        ),
        migrations.AddField(
            model_name='shoporder',
            name='order_status_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='pntmodel.orderstatus'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='shipping_address_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pntmodel.address'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='siteuser_set', related_query_name='siteuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='shopping_cart',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pntmodel.shoppingcart'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='siteuser_set', related_query_name='siteuser', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pntmodel.product'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='unit_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pntmodel.product'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='SKU',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pntmodel.maincategory'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pntmodel.siteuser'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pntmodel.product'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='account_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='expiry_date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='payment_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pntmodel.paymenttype'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='provider',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='value',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
