# Generated by Django 4.1 on 2023-11-13 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pntmodel', '0002_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pntmodel.siteuser'),
        ),
    ]
